# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Puppet IAC Team
email: ia_content@puppet.com
description: >- # this means to ignore newlines until "baseurl:"
  Team blog and list of maintained tools by and for the Puppet Infrastructure
  Automation Content Team.
baseurl: "/iac" # the subpath of your site, e.g. /blog
url: "https://puppetlabs.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: puppetlabs/iac
github_username: puppetlabs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-analytics
  - jekyll-sitemap

# settings for minima
header_pages:
  - docs.html
  - modules.html
  - tools.html

jekyll_analytics:
  GoogleAnalytics:
    id: UA-157301458-1
    anonymizeIp: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  # Use this to sort categories in modules.
  # needs to have a file for every category.
  module_categories:
    output: false
    order:
      - windows.md
      - linux.md
      - crossplatform.md
      - networking.md
      - other.md
  # Use this to sort categories in tools.
  # needs to have a file for every category.
  tool_categories:
    output: false
    order:
      - pdk.md
      - pdk-external.md
      - litmus.md
      - resource-api.md
      - misc-module-tools.md
      - i18n.md
  modules:
    output: true
  tools:
    output: true
  docs:
    output: true
  lifeofinternatpuppet:
    output: true
